spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
      
    data:
      repositories:
        enabled: true
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: jdbc:oracle:thin:@172.22.57.29:1521/DBMISC
    username: workeragreement
    password: desaworker22

management:
  endpoints:
    web:
      exposure:
        include: "info,health"   

rabbit:
   host: "172.22.91.218"
   port: "5672"
   username: "user_temporal"
   virtualhost: "temporal"
   password: "user_temporal"
   queue-response-name: "worker.request.queue"
   queue-read-time: 5000
   
externalServices:
   loginHiperionUrl: "https://api-gateway-hiperion-dev.tigo.com.gt/api/agreementmanagement/oauth2/token"
   queryContract: "https://api-gateway-hiperion-dev.tigo.com.gt/api/agreementmanagement/agreement"
   createContract: "https://api-gateway-hiperion-dev.tigo.com.gt/api/agreementmanagement/agreement"
   clientId: "ABH7tXiXu5j3ZQ8eZNhWWiJrYqpUmVJY"
   client_secret: "eCd1GmIaIKcem2otg36lDHu4po3MO2Zj"
   grant_type: "client_credentials"
   scope: "email"